version: "3.8"

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: frontend/fibonacci-spiral-matrix
    ports:
      - 3000:80
  backend:
    container_name: docker-go-c
    image: docker-go-i
    build:
      context: backend/fibonacciSpiralMatrix
    ports:
        - 8082:10000
