version: "2.21.0"

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: frontend/fibonacci-spiral-matrix
    ports:
      - 8080:8081
  backend:
    container_name: docker-go-c
    image: docker-go-i
    build:
      context: backend/fibonacciSpiralMatrix
    ports:
        - 8080:8080